### ISSUE TITLE
Issues with iso-8859-1 encoded SAMLResponse

### ISSUE THREAD

**Issue by monken** [bergie/passport-saml#130]
I'm working with an IdP that generates iso-8859-1 encoded SAMLResponses. I ended up writing a middleware that would decode the string with iconv-lite and re-encode it before passing it along to passport-saml. Otherwise the signature validation would fail ("Invalid signature").

```javascript
var iconvlite = require('iconv-lite');
var recodeSAMLResponse = function(req, res, next) {
  var response = req.body.SAMLResponse;
  if(!response) next();
  var buffer = new Buffer(response, 'base64');
  var decoded = iconvlite.decode(buffer, 'iso-8859-1');
  req.body.SAMLResponse = new Buffer(decoded).toString('base64');
  next();
}
```

I'm not sure how to integrate this with passport-saml. In line https://github.com/bergie/passport-saml/blob/8fa3381df8e0cc9eb29b25dbb8f80f87bd02af30/lib/passport-saml/saml.js#L429 the decoder forces utf-8.

**Comment by ploer** [comment]
If you'd like to put together a PR, I'd be open to a change where there's an optional config along the lines of `expectedPostResponseEncoding` that specifies a different encoding to use in the area you point to.

I'm not exactly sure what change you'd need to get this to work -- maybe just converting the buffer as 'binary' would do it?  Otherwise if you needed to use iconv-lite, I'd like to see that be an optional dependency, not something that everyone has to pull in.

Also, if you go down this path, please be sure to add a new test to cover it.

Otherwise, if your middleware is working for you, great. :-)
