### ISSUE TITLE
Support HTTP-Redirect binding for IdP to SP SLO

### ISSUE THREAD

**Issue by EnFinlay** [bergie/passport-saml#191]
From what I understand about SAML (which isn't comprehensive), there is currently no way of using `passport-saml` to generate a metadata file that will trigger the IdP to using `HTTP-Redirect` to send an assertion to the SP in a SP-initiated flow (see https://github.com/bergie/passport-saml/blob/master/lib/passport-saml/saml.js#L939).

Am I missing something?  Is it a hard fix to implement?  I'd be happy to give a PR a shot, but any advice on stumbling blocks would be greatly appreciated.

**Comment by pdspicer** [comment]
Beyond metadata, it looks like HTTP-Redirect binding from IdP to SP is not supported in authenticate() either (https://github.com/bergie/passport-saml/blob/master/lib/passport-saml/strategy.js#L73 shows support for processing POST responses only). So that'd need to be added as well. saml.js also doesn't seem to have support for base64 decoding response strings.

Sounds like your issue would be solved pretty easily by adding the additional line to metadata generation function, but actually being able to USE that endpoint with passport-saml would be a little more involved..

**Comment by EnFinlay** [comment]
Turns out there's a good reason that this isn't part of `passport-saml`.  See section 4.1.2 Step 5 of http://docs.oasis-open.org/security/saml/v2.0/saml-profiles-2.0-os.pdf.

```
In step 5, the identity provider issues a <Response> message to be delivered by the user agent
to the service provider. Either the HTTP POST, or HTTP Artifact binding can be used to transfer
the message to the service provider through the user agent. The message may indicate an error,
or will include (at least) an authentication assertion. The HTTP Redirect binding MUST NOT be
used, as the response will typically exceed the URL length permitted by most user agents.
```

Thanks to https://github.com/rohe/pysaml2/issues/163 for finally pointing me to why this was refusing to work.

Closing since it's outside the spec.

**Comment by pdspicer** [comment]
The use case that brought me to this issue was actually for IDP to SP SLO, which according to the spec MAY use HTTP-Redirect binding.. would you consider reopening this so as not to need a potentially duplicate issue for the support on the logout side?

**Comment by EnFinlay** [comment]
Sure thing.

**Comment by gregmsanderson** [comment]
Hi,

Is HTTP-Redirect binding now enabled/supported for SLO? At the end of the homepage it suggests it is, but if so, I'm not sure how to switch over from HTTP-POST:

_Passport-SAML has built in support for SLO including_

- Signature validation
- IdP initiated and SP initiated logouts
- Redirect and POST SAML Protocol Bindings

(My metadata currently uses POST which I assume is the default:
`SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"`)

Thanks

**Comment by stavros-wb** [comment]
@gregmsanderson If the IDP issues the LogoutRequest using the HTTP-Redirect then the passport-saml should work as advertised (the redirect will cause a logout). However the Binding method is configured on the IDP.
If you're using SimpleSamlPHP and want to try it out, just remove the Binding option from the IDP (it should use redirect by default for logout redirects)

**Comment by gregmsanderson** [comment]
@stavros-wb Hi, thanks. So does that mean I simply need to make _both_ a .get and a .post route to support both methods? Since Express would presumably otherwise not handle it, even if passport-saml would. Only I'm porting a legacy app and I see that in _its_ metadata, it says: HTTP-REDIRECT. However in the metadata exposed by the new app, using passport-saml, it says: HTTP-POST. So previously a GET would have arrived, and now a POST will. I assume.

Ideally I'd like to support current users (who've imported the metadata as it is _now_, with binding HTTP-REDIRECT), _and_ future users (who will get the _new_ metadata, with binding HTTP-POST)

**Comment by markstos** [comment]
@stavros-wb Does this issue need to remain open?

**Comment by stavros-wb** [comment]
@markstos I think it's fixed in https://github.com/bergie/passport-saml/commit/7674e18e2cc674132a9655936c2fca5dfc72af70
