### ISSUE TITLE
MultiSamlStrategy and InResponseTo are Incompatible by Default

### ISSUE THREAD

**Issue by gluxon** [bergie/passport-saml#334]
For every HTTP request, `MultiSamlStrategy` [creates a brand new `SAML` object](https://github.com/bergie/passport-saml/blob/master/multiSamlStrategy.js#L24). This in turn [creates a new `InMemoryCacheProvider`](https://github.com/bergie/passport-saml/blob/master/lib/passport-saml/saml.js#L68).

Meaning by default, the `InResponseTo` setting will always cause the middleware to fail with *"InResponseTo is not valid"*. Cache keys will never persist beyond the life time of a single HTTP request unless a custom `cacheProvider` is supplied.

I don't think the usage of two officially supported parts of the library should silently break. There are a 2 ways to fix this (that I see):

1. Add an error if a custom `cacheProvider` isn't supplied by the user when using the `MultiSamlStrategy.` Forcing users to reconfigure this library with an external cache store would workaround this issue.
2. Have `MultiSamlStrategy` hold onto its own`InMemoryCacheProvider` objects by default that it passes to new `SAML` instances. To do this securely, it would need to persist caches for each identity provider.

I lean towards 2, but unfortunately the current API design doesn't require each identity provider to be uniquely keyed. The `endpoint` SAML option gets close, but that can change with binding methods.

**Edit**: To be clear, I'm just hoping to open a discussion on how to best resolve this. I'm not demanding it to be fixed or trying to force a solution. I may be able to submit a pull request once we agree on something.

**Comment by gluxon** [comment]
I'm not sure how big of a problem it would be in practice, but it would allow a malicious identity provider to respond to an authentication request made to a different identity provider (assuming SAML response signing is off). If response signing is enforced, then not partitioning the cache should be fine.

@stavros-wb I just realized that you wrote MultiSamlStrategy. Thanks for that! It's been very useful to me.

**Comment by stavros-wb** [comment]
@gluxon can you try with the latest master?

**Comment by gluxon** [comment]
@stavros-wb Sorry for the late response, but this works! Thank you!

**Comment by crossan007** [comment]
It seems like 3.2.0 no longer defaults to `InMemoryCacheProvider` for `MultiSamlStrategy`  (possibly as of 224f25f71156a5908fc214bd146ad6e8274a0a9f).

Any ideas if this was an intentional change?

It seems like I should still be able to explicitly define a `InMemoryCacheProvider`  in my initialization options as  `cacheProvider`

**Comment by cjbarth** [comment]
What is the last version that worked as you expected @crossan007 ?

**Comment by crossan007** [comment]
I'm not actually sure.

I'm working on a new project and attempting to use the library.

I was searching through issues when I found the addition of the default cache provider for multi saml, and then dug through the commit history to locate where the default cache provider was removed when I realized what was added doesn't seem to work

**Comment by cjbarth** [comment]
If my memory serves me correctly, this was removed because we want consumers to be explicit about which cache provider they use. Feel free to specify an InMemoryCacheProvider yourself during construction. I see that this change was made for the 3.0.0 release. It is possible that some documentation is out of date. Please feel free to create a PR to fix any documentation.

**Comment by rfossella** [comment]
Hi.  I know this post/issue is really old, but was wondering if I was bumping into something similar with "@node-saml/passport-saml": "^5.0.0"
Is it **necessary** to create **my own custom cache** with multiple IdPs?  Do the later (latest) version of MultiSamlStrategy handle this?

The issue I sometimes face is logging in a user via **one** Idp (MS Entra) successfully; then a few seconds later logging into **another** IdP with different user (also MS Entra, but _different_ credentials) and MS throws message stating it can't find **FIRST** user in the **SECOND** IdP.

Is this related to this issue at all?  Something else?

**Comment by rfossella** [comment]
> Are those MS Entra IdPs behind same domain name / path? 

No, they are different domains which is the cause of confusion/concern.  Granted, a "regular" user will typically only be logging into their (single) domain.  My stress testing is meant to simulate an in-house user and outside user.

FYI: I did try the caching approach just to be sure and it had no affect.  I have since removed it.

**Comment by rfossella** [comment]
> I get a feeling that you did not quite understand what inresponseto cache is used for/what it contains. It does not cache responses. It caches ID values of authentication requests delivered to IdP.

Yes, I _originally_ thought it was caching responses and then realized it was meant to cache IDs/keys of auth requests.  I did get that working but since it did not address my primary issue I removed it.  Thanks for clarifying.
