### ISSUE TITLE
TypeError: self.error is not a function

### ISSUE THREAD

**Issue by ahavriluk** [bergie/passport-saml#386]
During migration to passport 1.1.0 got this error from my tests:
```    
TypeError: self.error is not a function

      at redirectIfSuccess (node_modules/passport-saml/lib/passport-saml/strategy.js:75:12)
      at DeflateRaw.requestToUrlHelper [as cb] (node_modules/passport-saml/lib/passport-saml/saml.js:350:16)
```

**Comment by markstos** [comment]
To show this an error in passport-saml, please create a PR that includes a failing test in the test suite. 

Here's the line being referred to:

https://github.com/bergie/passport-saml/blob/master/lib/passport-saml/strategy.js#L75

If you call `authenticate()` as a function instead of a method, then `this` would not be bound, resulting in the error. That is-- this could be an error in your own code, which is why I'm closing this until a failing test is contributed to demonstrate there's a bug in `passport-saml`
