### ISSUE TITLE
Cannot use dynamic values for entryPoint and cert

### ISSUE THREAD

**Issue by apriendeau** [bergie/passport-saml#52]
So currently, the lib requires you to specify the entry point on the app load but onelogin requires the url to be dynamic like `https://app.onelogin.com/trust/saml2/http-post/sso/{{random_id_generated}}`. Thoughts on how to do this currently because I might just be doing it wrong but this seems like a common use case where there are multiple companies.

``` javascript
passport.use(new SamlStrategy({
    issuer: 'someone',
  }, function(profile, done) {
    console.log('Auth with', profile);
    if (!profile.nameID ) {
      return done(new Error('No email found'), null);
    }
    return done(null, null)
  }))
```

``` javascript
  app.get('/saml/auth', function (req, res, next){
    return passport.authenticate('saml', { 
       entryPoint:  req.company.entryPoint,
       cert:  req.company.cert
    })(req, res, next)
  }, authentication.samlAuth)
```

**Comment by aecvargas** [comment]
I'm kind of going through the same implementation right now and fairly new to it but wondered if you guys could enlighten me a little. I have multiple organisations which have their `entryPoint` and `cert` set in the DB. I'm trying to use `passport.use` in both my `router.get()` and `router.post()` and applying the dynamic values. On an SP initiated login, a user is presented with a field to enter the `domain`. The `router.post()` retrieves this and does a lookup for that domain in the database and retrieves the strategy configs and used like so:

`strategyName = `${domain}-${strategyName} // strategyName being 'saml'` 
`passport.use(strategyName, createSamlStrategy(entryPoint, cert));`
`passport.authenticate....`

However, if the SSO flow is initiated via IdP (I'm using Okta to test with) then I can't actually do this because I don't have the `domain`, therefore I can't fetch the `entryPoint` and the `cert` to use in a new `passport.use` call in my callback function. My callback function does receive the `SAMLResponse`. So would it be better if I was to extract the data from the `SAMLResponse` and grab the `entryPoint` and `cert` values and use those values as well as using the `entryPoint` value as some sort of identifier for the `strategyName`? This would also mean that I need to change `${domain}-${strategyName}` above to use `entryPoint` instead of `domain`.

`...extractXmlData...`
`strategyName = `${entryPoint}-${strategyName} // strategyName being 'saml'`
`passport.use(strategyName, createSamlStrategy(entryPoint, cert));`

This would need that I would need an XML library to extract the data from the `SAMLResponse` right? I can get a hold of the `profile` but this would after it had been authenticated but what I'm trying to do is, set up and use the passport before it gets authenticated.

Does that make sense? Is this a valid way of doing it?
