### ISSUE TITLE
How to change callbackURL?

### ISSUE THREAD

**Issue by zhanggdc** [bergie/passport-saml#79]
Hi Dear

I am trying on your sample passport-saml-example.
I found IE always will be redirect to fixed-url "localhost:3000" after logo on  Feide openIdP.

I tried to set param "callbackUrl" with full url but no luck.

Could you please tell me how to change hostname&port of callbackURL?
Thanks in advance!

**Comment by ploer** [comment]
It's set either via `path` and `protocol` or else via `callbackUrl` as you tried.

One possibility is that setting is just somehow not being passed in correctly -- you could set a breakpoint in the passport-saml code to check that, perhaps.

You might also try looking at the request being sent to your provider (i.e., using the dev tools in your browser, and then reversing the base64 encoding -- there are some sites out there that you can just copy and paste saml requests into I think), and see if the callback url is being correctly passed to your provider.  If it is being passed correctly and being ignored, it could be due to the provider rejecting your request signature.

**Comment by molekilla** [comment]
Had the same issue, you need to change `issuer`

more here
http://stackoverflow.com/questions/24985023/redirect-localhost-instead-of-myserver-org3000-login-callback
