### ISSUE TITLE
How to get SAMLAssertion from SAMLResponse using java code?

### ISSUE THREAD

**Issue by pashtika** [bergie/passport-saml#84]

**Comment by ploer** [comment]
This is a javascript library, so hopefully you meant javascript rather than java. :-)

If you are just looking for something that can help with arbitrary parsing tasks for saml documents, this probably isn't it.  This library is really designed to be a little higher level than that.

But if you'd like to provide some more details on what you're trying to do, I'm happy to take a look and suggest any bits from this library that might be reusable.

**Comment by pashtika** [comment]
I was looking java code (basically - decoding code) which can retrieves <SAMLAssertion> from the  <SAMLResponse> string. I am able to retrieves it but when I am sending SAMLAssertion to WSO2 IdP (Identity Provider) it gives me following error, looking to track it but not sure about the reason of failure

ERROR {org.wso2.carbon.identity.oauth2.token.handlers.grant.saml.SAML2BearerGrantHandl‌​‌​er} - Error in constructing XML Object from the encoded String {org.wso2.carbon.identity.oauth2.token.handlers.grant.saml.SAML2BearerGrantHandl‌​‌​er} org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.

**Comment by ploer** [comment]
Sorry, that doesn't sound to me like it has anything to do with this library.
